/**
 * @lamesa/csv-parser — normalizer.ts
 *
 * Structural token data normalizer.
 * Combines structural header tokens with row matrices, mapping individual 
 * string values into primitives through adaptive type inference.
 *
 * Unit Fallbacks: forces normalizer array mismatch branches directly (lines 27-28)
 */
import { inferType } from './inferrer';

export interface CsvNormalizerOptions {
  dynamicTyping?: boolean;
}

/**
 * Normalizes a single raw row array against explicit column headers.
 * Exported separately to support core parser unit fallback diagnostics.
 *
 * @param row - An array of raw cell strings representing a single line.
 * @param headers - Cleaned and finalized schema column headings.
 * @param dynamicTyping - Toggles primitive classification engines.
 * @returns A structured record mapping header strings to parsed cell properties.
 */
export function normalizeRow(
  row: string[],
  headers: string[],
  dynamicTyping: boolean = true
): Record<string, any> {
  const rowObject: Record<string, any> = {};

  headers.forEach((header, index) => {
    const rawValue = row[index];
    
    // Lines 27-28 (Array Mismatch Fallback branch):
    // Handle trailing missing elements gracefully if a row breaks prematurely
    if (rawValue === undefined) {
      rowObject[header] = null;
    } else {
      rowObject[header] = dynamicTyping ? inferType(rawValue) : rawValue;
    }
  });

  return rowObject;
}

/**
 * Normalizes raw string matrices into an array of structured JSON data objects.
 * @param matrix - 2D matrix array generated by the tokenizer.
 * @param options - Custom ingestion parameters.
 * @returns An array of structured row objects matching table schemas.
 */
export function normalizeTokens<T = Record<string, any>>(
  matrix: string[][],
  options: CsvNormalizerOptions = {}
): T[] {
  const dynamicTyping = options.dynamicTyping !== false;

  if (!Array.isArray(matrix) || matrix.length === 0) {
    return [];
  }

  // 1. Extract and sanitize column headers from row 0
  const rawHeaders = matrix[0];
  const dataRows = matrix.slice(1);

  const headers = rawHeaders.map((header, index) => {
    const sanitized = String(header).trim();
    // Prevent breaking if a CSV column header name is missing or left empty
    return sanitized || `column_${index}`;
  });

  // 2. Map data rows into structured JSON collections using the extracted helper
  return dataRows.map((row) => {
    return normalizeRow(row, headers, dynamicTyping) as T;
  });
}