/**
 * @lamesa/csv-parser — normalizer.ts
 *
 * Structural token data normalizer.
 * Combines structural header tokens with row matrices, mapping individual 
 * string values into primitives through adaptive type inference.
 */
import { inferType } from './inferrer';

export interface CsvNormalizerOptions {
  dynamicTyping?: boolean;
}

/**
 * Normalizes raw string matrices into an array of structured JSON data objects.
 * @param matrix - 2D matrix array generated by the tokenizer.
 * @param options - Custom ingestion parameters.
 * @returns An array of structured row objects matching table schemas.
 */
export function normalizeTokens<T = Record<string, any>>(
  matrix: string[][],
  options: CsvNormalizerOptions = {}
): T[] {
  const dynamicTyping = options.dynamicTyping !== false;

  if (!Array.isArray(matrix) || matrix.length === 0) {
    return [];
  }

  // 1. Extract and sanitize column headers from row 0
  const rawHeaders = matrix[0];
  const dataRows = matrix.slice(1);

  const headers = rawHeaders.map((header, index) => {
    const sanitized = String(header).trim();
    // Prevent breaking if a CSV column header name is missing or left empty
    return sanitized || `column_${index}`;
  });

  // 2. Map data rows into structured JSON collections
  return dataRows.map((row) => {
    const rowObject = {} as Record<string, any>;

    headers.forEach((header, index) => {
      const rawValue = row[index];
      
      // Handle trailing missing elements gracefully if a row breaks prematurely
      if (rawValue === undefined) {
        rowObject[header] = null;
      } else {
        rowObject[header] = dynamicTyping ? inferType(rawValue) : rawValue;
      }
    });

    return rowObject as T;
  });
}